name: Build and Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_example:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        bazel_version:
          - 8.x
          - 9.x
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel_version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-${{ matrix.bazel_version }}
          repository-cache: true
          bazelrc: |
            build --color=yes
            build --show_timestamps
            common --enable_bzlmod

      - name: Build Example Module
        working-directory: ./examples
        run: bazel build :test_lib

      - name: Run Static Framework Test
        run: bash test_static_framework.sh
